In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [61]:
dataset_1 = pd.read_csv('./data/Ammani_Zaid.csv')
dataset_2 = pd.read_csv('./data/Bedouin.csv')
dataset_3 = pd.read_csv('./data/Falahi Dialect.csv')
dataset_4 = pd.read_csv('./data/falahia_merged_final.csv')
dataset_5 = pd.read_csv('./data/fullData-Amman.csv')
dataset_6 = pd.read_csv('./data/Karaki Sentences V2(1).csv')
dataset_7 = pd.read_csv('./data/urban(ammani) dialect.csv')
dataset_8 = pd.read_csv('./data/urban-1.csv')

In [62]:
for i in dataset_1.columns:
    print(i)

id
text
dialect
sentiment
confidence

In [63]:
dataset_1 = dataset_1.drop(columns=['id','dialect','confidence'])
dataset_1.head()

                                        text sentiment
0       قرأت إن في مشروع تطوير جديد بمنطقتنا   neutral
1      بدي أغير روتيني شوي، حاسس محتاج تغيير   neutral
2   سمعت إن في مطعم جديد افتتح بشارع الرينبو   neutral
3  الشغل هاي الأيام ضغط ما بيوصف، كتير تعبان  negative
4       والله زهقت من ناس بتحكي وما بتعمل شي  negative

In [64]:
for i in dataset_2.columns:
    print(i)

id
text
source
label_guess
confidence
classification

In [65]:
dataset_2 = dataset_2.drop(columns=['id ','source','label_guess','confidence'])
dataset_2.head()

                   text classification
0    حطوا الزاد للضيوف         Neutral
1             فزعنا لكم       Positive
2    عطني خبرك وخذ خبري        Neutral
3  دمنا واحد يا ولد عمي        Neutral
4                 قوكم         Neutral

In [66]:
for i in dataset_3.columns:
    print(i)

الجملة
المعنى
Confidence
التصنيف

In [67]:
dataset_3 = dataset_3.drop(columns=['Confidence','المعنى'])
dataset_3.head()

          الجملة   التصنيف
0        لُف علي   neutral
1         لد علي   neutral
2  مُد ايدك اُكل   neutral
3  مليح الحمدلله  positive
4     ابيش عندهم   neutral

In [68]:
for i in dataset_4.columns:
    print(i)

dialect
confidence
sentiment

In [69]:
dataset_4 = dataset_4.drop(columns=['confidence'])
dataset_4.head()

             dialect sentiment
0  أني ما إليش دوخلا   neutral
1          أَضي الضو   neutral
2    ما بِديش أَداوم   neutral
3            شو بدتش   neutral
4      وتش مالتش وتش  negative

In [70]:
for i in dataset_5.columns:
    print(i)

text
Dialect
sentiment
confidence

In [71]:
dataset_5 = dataset_5.drop(columns=['Dialect' , 'confidence'])
dataset_5.head()

                                                text sentiment
0                                بدي اروح عالبيت هلأ   neutral
1                      باجي بعد شوي، ما تستناني كتير   neutral
2  بدي اروح عالمول اليوم الصبح قبل ما يصير ازمة، ...   neutral
3  بدي راتب يكفيني لنص الشهر على الأقل، مش كل شهر...   neutral
4  باجي عالسوق أشتري شغلتين، وبرجع محمّل بكيسين ب...   neutral

In [72]:
for i in dataset_6.columns:
    print(i)

sentence
dialect
classification
confidence

In [73]:
dataset_6 = dataset_6.drop(columns=['dialect','confidence'])
dataset_6.head()

                                            sentence classification
0  البس جاكيتك عالسريع يابا، بدنا نروح عالمستشفى ...        neutral
1       لا تخاف، الدكتور رجل زقرت وما بيوجعك بالمرة.       positive
2  هات أغراضك خلينا نمشي عالمستشفى، الحرارة بلشت ...        neutral
3     أنا معك يما، فحص صغير عالمستشفى وبنرجع عالدار.        neutral
4  احرص وأنت طالع بالسيارة لا تدعثر، بدنا نلحق ال...        neutral

In [74]:
for i in dataset_7.columns:
    print(i)

label
text

In [75]:
dataset_7 = dataset_7[['text','label']]
dataset_7.head()

                                                text     label
0  لم تعجبني كباقي السلسلة و غير متحمس لقراءة الج...  Negative
1  كان المكان ممتاز والأمن والاستقبال اوكي . . ال...  Positive
2  القصة اجمالا مشوقة كونها تعتمد علي شخصيات يجمع...  Negative
3  اربع نجوم لولا الملل الذي اصابني في النهاية......     Mixed
4  رواية مملة .. اول صفحة يدل على ان الرواية دى ر...  Negative

In [76]:
for i in dataset_8.columns:
    print(i)

sentence
dialect
classification
confidence

In [77]:
dataset_8 = dataset_8.drop(columns=['dialect','confidence'])
dataset_8.head()

                              sentence classification
0  الناس هناك طيبين، وما في مشاكل كتير       positive
1       ابعتلي ازا  أنت موجود في البيت        neutral
2       هديك اليوم كنت عندو في الجامعة        neutral
3   والله الوضع مش تمام، في شوية مشاكل       negative
4         وين نفسك تروح طشة في المنطقة        neutral

In [ ]:
dataset_2.columns = dataset_1.columns
dataset_3.columns = dataset_1.columns
dataset_4.columns = dataset_1.columns
dataset_5.columns = dataset_1.columns
dataset_6.columns = dataset_1.columns
dataset_7.columns = dataset_1.columns
dataset_8.columns = dataset_1.columns

In [79]:
master_df = pd.concat([dataset_1,
                       dataset_2,
                       dataset_3,
                       dataset_4,
                       dataset_5,
                       dataset_6,
                       dataset_7,
                       dataset_8], ignore_index=True)

In [80]:
master_df.head()

                                        text sentiment
0       قرأت إن في مشروع تطوير جديد بمنطقتنا   neutral
1      بدي أغير روتيني شوي، حاسس محتاج تغيير   neutral
2   سمعت إن في مطعم جديد افتتح بشارع الرينبو   neutral
3  الشغل هاي الأيام ضغط ما بيوصف، كتير تعبان  negative
4       والله زهقت من ناس بتحكي وما بتعمل شي  negative

In [81]:
master_df.to_csv('./cleanedDataset/cleanedDataset.csv' , index=False)

In [82]:
for i in master_df['sentiment'].unique():
    print(i)

neutral
negative
positive
nan
Neutral
Positive
Negative
neutral
negative
positive
nuetral
Mixed

In [87]:
master_df['sentiment'] = master_df['sentiment'].replace([
    'Neutral',
    'neutral ',
    'nuetral',
    'Mixed'
],'neutral')

master_df['sentiment'] = master_df['sentiment'].replace([
    'Negative',
    'negative '
],'negative')


master_df['sentiment'] = master_df['sentiment'].replace([
    'Positive',
    'positive '
],'positive')

for i in master_df['sentiment'].unique().tolist():
    print(i)

neutral
negative
positive
nan

In [90]:
master_df[master_df['sentiment'].isna()]

                                  text sentiment
872                                NaN       NaN
873                                NaN       NaN
874                                NaN       NaN
875                                NaN       NaN
876                                NaN       NaN
...                                ...       ...
6940                               NaN       NaN
6941                               NaN       NaN
6942                               NaN       NaN
6943                               NaN       NaN
8138  يا عمي ليش هيك أنت واحد بارد وجه       NaN

[1032 rows x 2 columns]

In [91]:
master_df = master_df.dropna()

In [92]:
master_df[master_df['sentiment'].isna()]

Empty DataFrame
Columns: [text, sentiment]
Index: []

In [93]:
for i in master_df['sentiment'].unique().tolist():
    print(i)

neutral
negative
positive

In [94]:
master_df.to_csv('./cleanedDataset/cleanedDataset.csv' , index=False)